// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"context"
	"github.com/makki0205/ziken/api"
	"github.com/makki0205/ziken/db"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, config *AppConfig) app {
	dbHost := config.Host
	dbName := config.Name
	client := db.NewClient(ctx, dbHost, dbName)
	dbDB := db.NewDB(client)
	apiParams := api.APIParams{
		DB: dbDB,
	}
	apiAPI := api.NewAPI(apiParams)
	cmdApp := NewApp(apiAPI)
	return cmdApp
}

// wire.go:

type app struct {
	api api.API
}

type AppConfig struct {
	Name db.DBName
	Host db.DBHost
}

func NewApp(api2 api.API) app {
	return app{
		api: api2,
	}
}
